FROM python:3.9

RUN git clone --depth=1 https://github.com/bunnech/cellot.git
RUN cd ./cellot
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python setup.py develop
RUN wget -c https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/609681/processed_datasets_all.zip?sequence=1&isAllowed=y
RUN mv processed_datasets_all.zip?sequence=1 processed_datasets_all.zip
RUN unzip processed_datasets_all.zip
